### PR TITLE
make sharing settings update retro compatible

### PR DESCRIPTION
**Pull request by deeonwuli**
### :pushpin: References

-   **Issue:** Closes https://app.clickup.com/t/3k6nam5

### :fire: Testing
Run:
`yarn test`

#3k6nam5

### CODE REVIEW

**Review by anagperal — CHANGES_REQUESTED** [review]
thanks @deeonwuli ! This fix the tests and fixes the retrocompatibility but it's important to update the tests in ApplySharingSettingsUseCase.spec.ts to use data like in https://docs.dhis2.org/es_419/develop/using-the-api/dhis-core-version-238/sharing.html#new-sharing-object. If there is no time now for that, please add a TODO comment in the test explaining it for the future.

**Comment by anagperal** [comment]
@deeonwuli  Also I think that the task https://app.clickup.com/t/3k6nam5 it's not well linked because it's for Predictor-Extended app, do you mean this one https://app.clickup.com/t/3k6naef? (CC @MiquelAdell )

**Comment by MiquelAdell** [comment]
Jus bumping the correct link to track time for this task:
https://app.clickup.com/t/3k6naef

**Review by anagperal — CHANGES_REQUESTED** [review]
thanks @deeonwuli ! This code it's ok but as this PR has more time that the other task about warnings, it's better that you merge development into this branch and work with that updated code:

- Now instead of ApplySharingSettingsUseCase we have GetMetadataWithUpdatedSharingsUseCase, so update GetMetadataWithUpdatedSharingsUseCase in its function updateSharingSettings with this code
- Change names of tests (ApplySharingSettingsUseCase.metadata and ApplySharingSettingsUseCase.spec) according with new use case name GetMetadataWithUpdatedSharingsUseCase

**Review by anagperal — APPROVED** [review]
@deeonwuli thanks!!

**Pull request merged**
